p8105_hw1_yl5830
================
Yunjia Liu
2024-09-21

## Question1

### 1.Load the penguins dataset

``` r
data("penguins", package = "palmerpenguins")
penguins_df <- penguins
```

### 2.Describe the penguins dataset

Describe the dataset from several aspects, including the head of the
dataframe using head() function, the size of the dataframe using nrow()
& ncol(). In addition,calculate the mean of flipper_length_mm using
mean() function.(Note: already exclude all the possible missing numbers
in thr column of flipper_length_mm )

``` r
head(penguins,5)
```

    ## # A tibble: 5 × 8
    ##   species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
    ##   <fct>   <fct>              <dbl>         <dbl>             <int>       <int>
    ## 1 Adelie  Torgersen           39.1          18.7               181        3750
    ## 2 Adelie  Torgersen           39.5          17.4               186        3800
    ## 3 Adelie  Torgersen           40.3          18                 195        3250
    ## 4 Adelie  Torgersen           NA            NA                  NA          NA
    ## 5 Adelie  Torgersen           36.7          19.3               193        3450
    ## # ℹ 2 more variables: sex <fct>, year <int>

``` r
num_rows = nrow(penguins_df)
num_cols = ncol(penguins_df)
cat("The dataset has", num_rows, "rows and", num_cols, "columns.\n")
```

    ## The dataset has 344 rows and 8 columns.

``` r
mean_flipper_length = mean(penguins_df$flipper_length_mm, na.rm = TRUE)
cat("The mean flipper length is", mean_flipper_length, "mm.\n")
```

    ## The mean flipper length is 200.9152 mm.

Conclusion:

- variables: species, island, bill_length_mm, bill_depth_mm,
  flipper_length_mm, body_mass_g, sex, year
- size: 344 rows and 8 columns
- The mean flipper length is 200.9152 mm

### 3. Scatterplot of flipper_length_mm (y) vs bill_length_mm (x) with color points using the species variable

3.1 Remove rows with missing values to avoid errors in plotting

``` r
penguins_df_clean = na.omit(penguins_df)
```

3.2 Draw the scatterplot of flipper_length_mm vs bill_length_mm

``` r
scatterplot_flipper_bill = ggplot(penguins_df_clean, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) +
  geom_point() +
  labs(x = "Bill Length (mm)", y = "Flipper Length (mm)", title = "Flipper Length vs Bill Length by Species") +
  theme_minimal()

print(scatterplot_flipper_bill)
```

![](p8105_hw1_yl5830_files/figure-gfm/draw_plot-1.png)<!-- --> 3.3 Save
the scatterplot

``` r
ggsave(filename = "flipper_vs_bill_length_plot.png", plot = scatterplot_flipper_bill, width = 8, height = 6)
```

## Question2

1.  Create the data frame

Setting seed for reproducibility and generate the several variables
described as followed and combine into a dataframe.

- Random sample from standard normal distribution
- Logical vector indicating if the sample is greater than 0
- Character vector of length 10
- Factor vector with 3 levels

``` r
set.seed(123)

random_sample = rnorm(10)
logical_vector = random_sample > 0
character_vector = letters[1:10] 
factor_vector <- factor(sample(c("Level1", "Level2", "Level3"), 10, replace = TRUE))

df <- data.frame(random_sample, logical_vector, character_vector, factor_vector)
```

2.  Calculate the mean Take the mean of each variable.

``` r
mean_random_sample <- mean(df %>% pull(random_sample))
mean_logical_vector <- mean(df %>% pull(logical_vector))
mean_character_vector <- try(mean(df %>% pull(character_vector)), silent = TRUE)
```

    ## Warning in mean.default(df %>% pull(character_vector)): argument is not numeric
    ## or logical: returning NA

``` r
mean_factor_vector <- try(mean(df %>% pull(factor_vector)), silent = TRUE) 
```

    ## Warning in mean.default(df %>% pull(factor_vector)): argument is not numeric or
    ## logical: returning NA

``` r
cat("Mean of random sample:", mean_random_sample, "\n",
    "Mean of logical vector:", mean_logical_vector, "\n",
    "Mean of character vector (attempt):", mean_character_vector, "\n",
    "Mean of factor vector (attempt):", mean_factor_vector, "\n")
```

    ## Mean of random sample: 0.07462564 
    ##  Mean of logical vector: 0.5 
    ##  Mean of character vector (attempt): NA 
    ##  Mean of factor vector (attempt): NA

3.  Explanation：Coercion using as.numeric() Coerce the logical,
    character, and factor variables to numeric and see what happens.

``` r
numeric_logical <- as.numeric(df$logical_vector)
numeric_character <- as.numeric(df$character_vector)
numeric_factor <- as.numeric(df$factor_vector)

numeric_logical
numeric_character
numeric_factor
```

As the results shown above, here’s some explaination regarding the mean
calculation:

- random_sample: be able to take the mean since it’s numeric.
- logical_vector: Coercing a logical vector to numeric works because
  TRUE becomes 1 and FALSE becomes 0. This is why the mean of the
  logical vector works.
- character_vector:Coercing a character vector to numeric will return NA
  values with a warning, because character strings cannot be directly
  converted to numbers.
- factor_vector: Coercing a factor to numeric will convert the factor
  levels to their underlying numeric representation (i.e., the integer
  values corresponding to the levels). This explains why taking the mean
  of a factor doesn’t work unless first convert it to numeric.

Conclusion:

- the mean of numeric and logical variables in R can be calculated
  because logical values are treated as 1 and 0.
- the mean of character or factor variables cannot be calculated without
  coercing them to numeric first.
- Coercing character data to numeric will fail, but coercing factors
  will convert them to their underlying numeric levels.
